version: "3"

services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  migrate:
    restart: on-failure
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@localhost:5433/${POSTGRESQL_DBNAME}?sslmode=${POSTGRESQL_SSL_MODE}",
      ]
    command: ["up"]
    depends_on:
      - postgres
    network_mode: host

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRESQL_DBNAME}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
